version: 2.1
jobs:
  build:
    docker:
      - image: mono
    steps:
      - checkout
      - run: msbuild -Restore:true /p:Configuration=Release DockerEffectProcessor.csproj
      - persist_to_workspace:
          root: bin/Release/net472/
          paths:
            - DockerEffectProcessor.dll
  publish:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete ${CIRCLE_TAG} ./artifacts/
workflows:
  version: 2
  default:
    jobs:
      - build:
          pre-steps:
            - run:
                name: "Install git and SSH client"
                command: |
                  apt-get update && apt-get install -y git openssh-client
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
